"""Stochastic six-vertex model, sampled exactly by sequential propagation.

This is a different model from the DWBC one in the rest of the package, and it
covers a regime DWBC cannot reach exactly.

At each vertex the outgoing arrows are drawn from a genuine probability
distribution conditioned on the incoming ones:

    (h_in, v_in) = (0,0) -> (0,0)                     w.p. 1
                   (1,1) -> (1,1)                     w.p. 1
                   (1,0) -> (1,0) w.p. b1, (0,1) w.p. 1-b1
                   (0,1) -> (0,1) w.p. b2, (1,0) w.p. 1-b2

Because the weights are stochastic, a configuration can be generated by
sweeping the lattice once in an order that respects the flow of arrows. No
Markov chain, no coalescence, no mixing time: the result is an exact sample in
O(N^2) time.

In six-vertex weight language this is a1 = a2 = 1, B = b1*b2,
C = (1-b1)(1-b2), giving

    Delta = (b1 + b2) / (2 sqrt(b1 b2)) >= 1

by AM-GM, with equality iff b1 = b2. So the stochastic model lives entirely in
the ferroelectric regime -- exactly the Delta > 1 panel of Figure 18 of
arXiv:2309.12495 -- which for domain-wall boundary conditions is the regime
where exact sampling is hardest.
"""
from __future__ import annotations

import numpy as np


def sample(n, b1, b2, seed=None, initial="step"):
    """Sample the stochastic six-vertex model on an n x n grid.

    Returns (h, v) where h[i, j] is the horizontal arrow entering vertex
    (i, j) from the left and v[i, j] the vertical arrow entering from below.
    Row 0 is the bottom.

    `initial="step"` puts an incoming arrow on every left-boundary row and
    none on the bottom -- the step initial condition, and the free-exit
    boundary used in the figure.
    """
    if not (0.0 < b1 < 1.0 and 0.0 < b2 < 1.0):
        raise ValueError(f"b1 and b2 must lie strictly in (0,1); got {b1}, {b2}")
    rng = np.random.default_rng(seed)

    # h[i, j]: horizontal arrow entering (i, j);  v[i, j]: vertical entering
    h = np.zeros((n, n + 1), dtype=np.int8)
    v = np.zeros((n + 1, n), dtype=np.int8)

    if initial == "step":
        h[:, 0] = 1          # an arrow enters every row from the left
        v[0, :] = 0          # nothing enters from below
    else:
        raise ValueError(f"unknown initial condition {initial!r}")

    # Sweep so that both inputs of a vertex are already fixed when we reach it.
    for i in range(n):
        for j in range(n):
            hi, vi = h[i, j], v[i, j]
            if hi == 1 and vi == 1:
                ho, vo = 1, 1
            elif hi == 0 and vi == 0:
                ho, vo = 0, 0
            elif hi == 1 and vi == 0:
                if rng.random() < b1:
                    ho, vo = 1, 0
                else:
                    ho, vo = 0, 1
            else:                       # hi == 0 and vi == 1
                if rng.random() < b2:
                    ho, vo = 0, 1
                else:
                    ho, vo = 1, 0
            h[i, j + 1] = ho
            v[i + 1, j] = vo
    return h, v


def height_function(h, v):
    """Height function of a configuration, for plotting.

    H(i, j) counts the paths passing weakly below-left of the point, which is
    the standard height for this model.
    """
    n = v.shape[1]
    H = np.zeros((n + 1, n + 1), dtype=np.int32)
    # cumulative count of vertical arrows crossing each row boundary
    H[1:, 1:] = np.cumsum(v[1:n + 1, :], axis=1).cumsum(axis=0)[:, :]
    return H


def delta(b1, b2):
    return (b1 + b2) / (2.0 * np.sqrt(b1 * b2))
